name: PR - Pull Request Pipeline
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  FormatingStandart:
    name: Lint and Prettier check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Dependencies
        run: npm install
      - name: Lint and Prettier check
        run: |
          npm run lint
          npm run format
